### ISSUE TITLE
Allow aggregates method to be used multiple times in a class

### ISSUE THREAD

**Issue by flyingzumwalt** [projecthydra-labs/activefedora-aggregation#11]
activefedora-aggregation's aggregates method can be used only once in an activefedora base class/sub-class. If using aggregates multiple times should work, then there is a bug.

**Comment by jcoyne** [comment]
Per a conversation with @elrayle An object can only have one ORE aggregation, so this ticket is not a valid request.  We'll make some higher level function that combines/separates objects and collections at a higher level in PCDM.

**Comment by jpstroop** [comment]
So if you wanted multiple aggregations, you'd have to create separate Objects for each (presumably associated with a common parent via `hasMember`)?

It's not clear to me that PCDM has this limitation. Or is this a limitation being imposed by the scope of the current sprint?

**Comment by elrayle** [comment]
I've sent a note to Rob Sanderson for clarification on ORE ontology handling of multiple aggregations.  The crux of the problem seems to be coming down to the head predicate which indicates the start of the list.  I believe the problem is that there is one subject (always only one subject) which has one head predicate pointing to the first proxy object.  If there was a second head, how would you know which aggregation each head applies to?  For Collections and Objects, they also share the same predicate (pcdm.hasMembers).  For relatedObjects, the predicate is ore.aggregates.  So, ultimately, at least conceptually, we are trying to maintain 3 lists in one Collection.

**Comment by elrayle** [comment]
To be more precise and hopefully avoid confusion, the predicate for the head of an ordered aggregation is IANA.first.

**Comment by jpstroop** [comment]
Yeah, `iana:first` was my question. I'm in a room with Rob now. We'll try to discuss over lunch and one of us will report back.

**Comment by jpstroop** [comment]
@azaroth42 : Ping!

**Comment by jpstroop** [comment]
Short answer: yes, only one aggregation per Object. So if you want multiple, you need subordinate Objects/Collections. Question: is `ore:aggregates` the correct predicate for these, or does PCDM need a new predicate?

**Comment by azaroth42** [comment]
Because pcdm:Object *is* an ore:Aggregation.  They're not separate resources.  If you want to have multiple sets, you need to use multiple objects/collections.

I think we should raise the aggregates predicate question on the PCDM repo. (and this ticket thus remains closed)

**Comment by elrayle** [comment]
The question comes up in multiple contexts.  I raise them hear for discussion...

**Collections**
Have the potential for 3 (conceptual) aggregations.  Can these be combined?  If not, how do we want to handle them?
* Collection pcdm:hasMember Collection
* Collection pcdm:hasMember Object
* Collection ore:aggregates Object (related object)

In the current implementation, member collections and objects are held in the same aggregation.  They share the same predicate, pcdm:hasMember.

Questions:
* Can related objects be part of the same aggregation?  Note that related objects use ore:aggregates predicate.

**Objects**
Have the potential for 4 (conceptual) aggregations.
* Object pcdm:hasMember Object
* Object pcdm:hasFile File
* Object ore:aggregates Object (related object)
* Object pcdm:hasRelatedFile File (related file)

In the current implementation, only hasMember Object is defined as an aggregation.  There has been discussions suggesting that hasFile File should also be an aggregation.

Questions:
* Should hasFile File and hasRelatedFile File be unordered aggregations?
* Can these all be combined into a single aggregation? (messy)
* Should an additional object be created in Fedora for each of the aggregations?

**Comment by elrayle** [comment]
The final question raises the possibility that pcdm:Collection and pcdm:Object not be ore:aggregations themselves, but should hold an aggregation for each usage.  For example...

* Collection (ldp:RdfSource, pcdm:Collection)
 * pcdm:hasAggregation Collections (ldp:IndirectContainer, ore:aggregation)
 * pcdm:hasAggregation Objects (ldp:IndirectContainer, ore:aggregation)
 * pcdm:hasAggregation RelatedObjects (ldp:IndirectContainer, ore:aggregation)

Collection descriptive and access metadata will be on Collection.

NOTE: This implies that collections and objects can be ordered separately.  If collections and objects should be intermixed in the ordering, then Collections and Objects would need to be a single aggregation.

* Object (ldp:RdfSource, pcdm:Object)
 * pcdm:hasAggregation Objects (ldp:IndirectContainer, ore:aggregation)
 * pcdm:hasAggregation Files (ldp:IndirectContainer, ore:aggregation)
 * pcdm:hasAggregation RelatedObjects (ldp:IndirectContainer, ore:aggregation)
 * pcdm:hasAggregation RelatedFiles (ldp:IndirectContainer, ore:aggregation)

* File (ldp:RdfSource, pcdm:File)
 * pcdm:contains binary_blobs (ldp:NonRdfSource)

This obviously has implications for the Fedora structures suggested thus far.

**Comment by azaroth42** [comment]
Raising questions in a closed issue doesn't seem like the right place for such a discussion.

**Comment by flyingzumwalt** [comment]
Based on discussion in the Scrum, reopening the ticket.

**Comment by elrayle** [comment]
To handle PCDM:Collection
      aggregates :members, :predicate => RDFVocabularies::PCDMTerms.hasMember, :class_name => "ActiveFedora::Base"

**Comment by elrayle** [comment]
Collection pcdm:hasMember Collection
    Collection pcdm:hasMember Object
    Collection ore:aggregates Object (related object)

**Comment by jcoyne** [comment]
one note, pcdm:Object#files is not an aggregation, it's just a ldp:DirectContainer.

**Comment by flyingzumwalt** [comment]
We've decided that this is actually a pcdm issue.  Re-routing discussion to projecthydra-labs/hydra-pcdm#14
