### ISSUE TITLE
Test/Implement Node Deletion Functionality

### ISSUE THREAD

**Issue by terrellt** [projecthydra-labs/activefedora-aggregation#20]
If you remove a member it should delete it via the corresponding proxy.

**Comment by atz** [comment]
Or proxies?

**Comment by escowles** [comment]
Is this done?  What's needed beyond what's in [ordered_proxy_spec.rb](https://github.com/projecthydra-labs/activefedora-aggregation/blob/master/spec/active_fedora/aggregation/ordered_proxy_spec.rb#L15)?

**Comment by terrellt** [comment]
@escowles Yes, I think it's done. Closed in AF.
