### ISSUE TITLE
fail to add additional items to an aggregation

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/activefedora-aggregation#24]
See new tests in association_spec:
* it "should return an updated array of generic_files"
* it "should return an updated array of generic_files when generic_files is empty"

NOTE: In both cases the association container is unchanged.  In the first test, there are two generic_files in the container at the start of the test and two generic_files in the container at the end of the test.  For the second test, the container is empty at the start and end.

**Comment by terrellt** [comment]
These tests are here: https://github.com/projecthydra-labs/activefedora-aggregation/commit/c5e94347380d28819de00f2eadf5e026be6ab4cf

**Comment by elrayle** [comment]
I've made a PR for that includes the tests.  Just waiting for someone to merge.  https://github.com/projecthydra-labs/activefedora-aggregation/pull/26

**Comment by terrellt** [comment]
@elrayle There are some comments in that PR, could you take a look?

**Comment by jcoyne** [comment]
@elrayle can this be closed?

**Comment by elrayle** [comment]
Fixed by PR #26
