### ISSUE TITLE
ore:proxyIn is pointing the wrong direction

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/activefedora-aggregation#30]
It should point from the proxy to the aggregation.

**Comment by jcoyne** [comment]
Blocked by https://github.com/projecthydra/active_fedora/pull/788

**Comment by jcoyne** [comment]
@terrellt I think this can be closed now, right?

**Comment by terrellt** [comment]
@jcoyne I don't think I did anything with this. So...maybe?
