### ISSUE TITLE
related_objects.delete should return deleted object (not array) or nil

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/activefedora-aggregation#36]
When the following code is used to remove a related object from a collection/object, it has unexpected behaviors.
```
parent_collection.related_objects.delete child_related_object
```

* if child_related_object is present and deleted -
     CURRENT: returns [child_related_object]
     DESIRED: return child_related_object

* if child_related_object is missing, but other related objects exist - returns [child_related_object]; should return child_related_object
     CURRENT: returns [child_related_object]
     DESIRED: return nil

* if related objects is empty
     CURRENT: raises error - ActiveFedora::ObjectNotFoundError: Can't reload an object that hasn't been saved
     DESIRED: return nil

**Comment by elrayle** [comment]
See also https://github.com/projecthydra-labs/activefedora-aggregation/issues/34, which describes similar issues with members.

**Comment by elrayle** [comment]
NOTE: Tracking this down a little further, I don't get the exception to raise in all cases.
```
subject = Hydra::PCDM::Collection.create
subject.members << object2
subject.reload.related_objects.include? object1  # raise error
```

It does not fail if I do the following...
```
subject = Hydra::PCDM::Collection.create
subject.members << object2
x = subject.reload.related_objects
x.include? object1   # => false
```

**Comment by jcoyne** [comment]
:arrow_up: That doesn't make any sense to me. `x` should be able to be factored out, meaning the code is identical.

**Comment by jcoyne** [comment]
Are you running this in a console window? Because then there's an implicit `#inspect` call happening (when you do `x = subject.reload.related_objects`), that causes the members to get loaded.

**Comment by jcoyne** [comment]
Wait, I'm not seeing an ObjectNotFound exception, instead, I'm seeing this:

```
RuntimeError: Couldn't find reflection
	from /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/active_fedora-57ac75495fca/lib/active_fedora/associations/collection_association.rb:345:in `find_reflection'
	from /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/active_fedora-57ac75495fca/lib/active_fedora/associations/association_scope.rb:28:in `block in add_constraints'
	from /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/active_fedora-57ac75495fca/lib/active_fedora/associations/association_scope.rb:22:in `each'
	from /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/active_fedora-57ac75495fca/lib/active_fedora/associations/association_scope.rb:22:in `each_with_index'
	from /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/active_fedora-57ac75495fca/lib/active_fedora/associations/association_scope.rb:22:in `add_constraints'
	from /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/active_fedora-57ac75495fca/lib/active_fedora/associations/association_scope.rb:16:in `scope'
	from /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/active_fedora-57ac75495fca/lib/active_fedora/associations/association.rb:78:in `association_scope'
	from /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/active_fedora-57ac75495fca/lib/active_fedora/associations/association.rb:67:in `scope'
	from /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/active_fedora-57ac75495fca/lib/active_fedora/associations/collection_association.rb:315:in `scope'
	from /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/active_fedora-57ac75495fca/lib/active_fedora/associations/collection_association.rb:118:in `include?'
	from /Users/justin/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/bundler/gems/active_fedora-57ac75495fca/lib/active_fedora/associations/collection_proxy.rb:836:in `include?'
```

Is that what you see too?

**Comment by jcoyne** [comment]
as `related_objects` is not an ore:aggregation (it's an indirect container) maybe this issue should be moved to https://github.com/projecthydra/active_fedora

**Comment by elrayle** [comment]
I agree the code 'should' be identical.  The error shows up running rspec.

Test: https://github.com/projecthydra-labs/hydra-pcdm/blob/new_service_for_removing/spec/hydra/pcdm/services/collection/remove_related_object_spec.rb        
Context:  context 'when related object is missing' 

Really just the first two tests when related_objects is empty.  I got the second set of code to work by breaking into the test with binding.pry.  If I execute the first set, it raises the exception every time.  If I execute the second set, I get the expected result of false.

**Comment by elrayle** [comment]
Moved to https://github.com/projecthydra/active_fedora/issues/805.
