### ISSUE TITLE
Proxy should assert proxyIn

### ISSUE THREAD

**Issue by jcoyne** [projecthydra-labs/activefedora-aggregation#38]
Possibly caused by https://github.com/projecthydra-labs/activefedora-aggregation/commit/6a260f672bc4a4aed66117589e49789e51e7fcc9

because of the inverse_of on the has_and_belongs_to_many association being removed.

It seems to work correctly in 0.2.1

**Comment by flyingzumwalt** [comment]
For a test that shows this (and a sample of code that would use it), see the [aggregated_by branch](https://github.com/projecthydra-labs/activefedora-aggregation/compare/aggregated_by)
