### ISSUE TITLE
Add << functionality for aggregations

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/activefedora-aggregation#44]
The last line << should add an object to the members aggregation.  << should append an object whether members is empty or has other objects already in the aggregation.

```ruby
class DummyObject < ActiveFedora::Base
  aggregates :members, predicate: RDFVocabularies::PCDMTerms.hasMember, class_name: "ActiveFedora::Base"
end

do_parent = DummyObject.new
do_child1 = DummyObject.new
do_child2 = DummyObject.new
do_child3 = DummyObject.new

do_parent.members = [do_child1,do_child2]   # => [do_child1,do_child2]
do_parent.members << do_child3                   # => [do_child1,do_child2,do_child3]
```

**Comment by jcoyne** [comment]
I was unable to find any deficiencies in the current code. Never the less, I added more tests: https://github.com/projecthydra-labs/activefedora-aggregation/pull/49

**Comment by elrayle** [comment]
I'll see if I can get a test together for this.  It seems to work sometimes and not others.
