### ISSUE TITLE
delete from members should also remove the child from the results filter get methods

### ISSUE THREAD

**Issue by elrayle** [projecthydra-labs/activefedora-aggregation#52]
When deleting from an association in memory, the deleted child should be removed from the association and filter methods should also not contain the deleted child.

The following test, when added to filter_spec.rb, demonstrates this failure...

```ruby
  describe "deleting" do
    let(:image) { Image.new }
    let(:obj1) { TestObject.new }
    let(:obj2) { TestObject.new }
    let(:obj3) { TestObject.new }
    let(:col1) { TestCollection.new }
    let(:col2) { TestCollection.new }
    let(:col3) { TestCollection.new }

    before do
      image.members = [col1,obj1,obj2,col2,obj3,col3]
    end

    it "deletes from all members" do
      image.delete obj2
      expect(image.members).to eq [col1,obj1,col2,obj3,col3]
      expect(image.child_objects).to eq [obj1,obj3]
    end
end
```

**Comment by jcoyne** [comment]
I think the problem is that you shouldn't use `image.delete(obj)` but `image.child_objects.delete(obj)`

**Comment by jcoyne** [comment]
When you call `image.delete()` you are deleting the image object itself.

**Comment by elrayle** [comment]
Yep, that was a typo in that test.  The pcdm code has the correct syntax.  

I have chased this down further to an odd problem that only occurs if you get the members prior to the delete AND you use rspec expect to validate the list of members is correct prior to the delete.  See the two versions of the same test below.  When added to filter_spec, one fails and one passes.

```ruby
  describe "delete fails" do
    before do
      image.child_objects = [test_object]
      expect( image.child_objects ).to eq [test_object]   # FAILS when using this line
      image.child_objects.delete(test_object)
    end

    subject { image.child_objects }

    it { is_expected.to eq [] }
  end

  describe "delete works" do
    before do
      image.child_objects = [test_object]
      image.child_objects                        # WORKS when using this line
      image.child_objects.delete(test_object)
    end

    subject { image.child_objects }

    it { is_expected.to eq [] }
  end
```

**Comment by jcoyne** [comment]
@elrayle I see. this is because `image.child_objects` is just returning the proxy object, where as `expect( image.child_objects ).to eq [test_object]` is causing the proxy to load its values.  You can achieve the same failure with `image.child_objects.to_a`

**Comment by elrayle** [comment]
Any solution or recommended better way to write the test?  From the test I wrote, it only seems to happen when the expect() is used.  Could it also happen if the get is outside the context of expect()?  The pattern of doing a delete followed by a get is very common.

**Comment by jcoyne** [comment]
If you've loaded the association and then you delete something, then you want an updated look at the association, you should pass it `true` so it reloads:

```
      image.child_objects = [test_object]
      image.child_objects.to_a  #This causes the results to get loaded and cached.
      #=> [test_object]
      image.child_objects.delete(test_object)  # This isn't invalidating the cache
      image.child_objects.to_a  # So returns the cached object
      #=> [test_object] 
      image.child_objects(true).to_a  # Forced a cache invalidation.
      #=> []
```

**Comment by jcoyne** [comment]
I suspect the cache isn't invalidated because the indirectly_contains association isn't setting `stale_state` correctly

**Comment by elrayle** [comment]
Is this something requiring a fix or a change in usage?  Using (true), what impact does this have for save and reload?  Does this only set stale_state which invalidates the cache?

**Comment by jcoyne** [comment]
I think the indirectly_contains association should provide a stale_state so that when you remove things, it'll automatically invalidate the cache.
